Lock JDK version

diff --git a/main b/main
--- a/main
+++ b/main
@@ -9,9 +9,9 @@ dir=`dirname $0`
 base_dir=`realpath "$dir"/env`
 
 # Manual downloads
-jdk8_tar="jdk-8uXXX-linux-x64.tar.gz"
+jdk8_tar="jdk-8u131-linux-x64.tar.gz"
 if test ! -f "$dir"/downloads/"$jdk8_tar" ; then
-  printf '%s\n%s\n%s\n%s\n' "[MISSING FILE]: downloads/$jdk8_tar" "Please download the latest Oracle Java SE 8 JDK from" "\"http://www.oracle.com/technetwork/java/javase/downloads/index.html\"" "and move/rename the file to \"downloads/$jdk8_tar\"." 1>&2
+  printf '%s\n%s\n%s\n%s\n' "[MISSING FILE]: downloads/$jdk8_tar" "Please download Oracle Java SE Development Kit 8 (JDK) from" "\"http://www.oracle.com/technetwork/java/javase/downloads/index.html\"" "and move/rename the file to \"downloads/$jdk8_tar\"." 1>&2
   exit 1
 fi
 
